### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by tzapzoor**
#19 Fixed this as well.
The only thing that isn't elegant is that you have to **manually** add the environment paths for the Microsoft compiler and for Dr. Memory before running Robocheck.

### CODE REVIEW

**Comment by andreituicu** [comment]
Can you please also update the README in this pull request with all the steps required for installing and getting Robocheck running on Windows? These kind of details tend to get lost if they are not documented.

**Comment by tzapzoor** [comment]
Sure. :)

**Comment by tzapzoor** [comment]
I've updated the README. If you think it's appropriate I can merge the pull request. :+1: 
@andreituicu, @lauravasilescu

**Comment by andreituicu** [comment]
Looks really good! Just one question: Do we really need the entire Visual Studio? Can't we get only cl and nmake?

**Comment by tzapzoor** [comment]
[I found this on SO](http://stackoverflow.com/questions/22290501/can-i-download-the-visual-c-command-line-compiler-without-visual-studio). It's pretty old, but I think it's still valid.

**Comment by andreituicu** [comment]
Ok, perfect! Merging this PR.

**Pull request merged**
